name: server
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  leancloud_storage: ^0.6.2
  leancloud_official_plugin: ^1.0.0-beta.12

dev_dependencies:

flutter:

  uses-material-design: true